# Install PyTorch

Run in command line OR in terminal of VSCode 

`pip install torch`

In [5]:
# Check if PyTorch was installed successfully --- run in command line OR terminal of VSCode [pip install torch]
import torch
torch.rand(2, 3)

tensor([[0.9675, 0.2682, 0.0698],
        [0.0939, 0.6720, 0.4819]])

In [14]:
# to check if your GPU driver and CUDA is enabled and accessible by PyTorch
torch.cuda.is_available()

False

In [12]:
torch.cuda.is_available()

False

# TENSORS
Tensors are a specialized data structure that are very similar to arrays and matrices. Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators.

## Initializing a Tensor

**Directly from Data**

In [7]:
import torch
data = [[1, 2], [3, 4]]     # define an arbitrary 2-D array and store it in a variable named 'data'
x_data = torch.tensor(data) # convert the array to tensor
x_data

tensor([[1, 2],
        [3, 4]])

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see [Bridge](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label) with NumPy).

In [16]:
import numpy as np
np_array = np.array(data)   # Convert 'data' from the previous cell to an np-array and assign it to a variable 'np_array'
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

**With Random or Constant array**

In [17]:
shape = (2,3)       # define a variable 'shape' to store the shape or dimension of the tensor to create
rand_tensor = torch.rand(shape)     # .rand creates random tensor of shape defined by the variable 'shape', i.e., (2 rows, 3 columns)
ones_tensor = torch.ones(shape)     # .ones creates a tensor with all '1' with defined shape
zeros_tensor = torch.zeros(shape)   # .zeros creates a tensor with all '0' with defined shape

print(f"Random Tensor: \n {rand_tensor} \n")    # f".." - for formatted string
print(f"Ones Tensor: \n {ones_tensor} \n")      # \n - for new line break
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8000, 0.0978, 0.0882],
        [0.6401, 0.1165, 0.6653]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
